### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Vries14** [kartoza/healthyrivers#151]
# Bug report

1. Click on search icon
2. Under the "category" filter, select "translocated'.
3. Click on "apply filter"
4.Click to open "sites(195)"
5. Select "amandel"

# Error

The only thing on screen is a navigation icon
![Search.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6952abafc89a0011b75b37/125516c66e82c728ace21e0d46db919b31818bebc3abaf51ab57f5973d047d317c05f6782584b57ae7117a585d0d4eac400a584dadfddb78b4aa2e32db025fb28c341521842f1bbeb98515be04b9248f4e81b3b48c4fc8ef2f68.png)

# Expected behaviour

The map should not disappear when doing a search.

**Comment by meomancer** [comment]
hi @Vries14 
when clicking a site in sites, it is zooming into that site and showing the detail at side panel. Should we not zoom it into the site? (because it will quite hard to see which site that we are looking now if we don't zoom into it)

**Comment by Vries14** [comment]
@meomancer 
Zooming into the site is efficient, but wouldn't it be better if we could be able to zoom into the site and also see where the site is located on the map instead of the map going blank?

**Comment by gubuntu** [comment]
tha map doesn't go blank, it just zooms in way too close. So zoom in, but to a useful zoom level, perhaps 18.

**Comment by meomancer** [comment]
this issue is fixed by this PR: https://github.com/kartoza/django-bims/pull/249

Before: (zoom to max level)
![selection_057](https://user-images.githubusercontent.com/4530905/44331128-e7722c80-a492-11e8-8352-75b56a9da0b3.png)

After: (zoom to maxmum level 18)
![selection_058](https://user-images.githubusercontent.com/4530905/44331150-f35dee80-a492-11e8-9b21-b450ac86e2bf.png)

**Comment by Vries14** [comment]
maximum zoom levels are now more functional.
