### ISSUE TITLE
Create rectangular select function

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/healthyrivers#246]
# Problem

Please create a square-select function to zoom easily into an area.

# Solution
We can already do this with shift-drag - can we put a tooltip somewhere indicating this @Dimas?

Child of #258

**Comment by dimasciput** [comment]
@carina1000 any idea where should we put this?

**Comment by gubuntu** [comment]
In the initial info popup for the site? Some basic user documentation?

**Comment by carina1000** [comment]
What exactly does this function do? Could anyone send me an example of this? cc @gubuntu @dimasciput

**Comment by gubuntu** [comment]
left-click-shift-drag a rectangle to zoom into the map.

**Comment by carina1000** [comment]
Child of #258

**Comment by gubuntu** [comment]
@carina1000 I moved the child link into the OP else it has no effect. 

Also please ensure that any funcitonality or enhancements that will benefit LEDET as well as healthyrivers should go into django-bims so it gets through to both instances - like this one.

**Comment by timlinux** [comment]
@carina1000 it lets you zoom to a smaller area of the map by dragging a square on the map. As has been mentioned here, we already have the functionality, we just need a 'navigating' tips popup somewhere that lists the basic map navigation functions:

Map usage:

* hold left mouse button and drag to pan the map left, right, up, down
* press shift, hold left mouse button and drag the mouse to zoom to a new area by drawing a box
* click on circular cluster markers to zoom in to that cluster
* click on square site markers on the map to discover more about it
* use the scroll wheel on your mouse while hovering over the map to zoom in and out

@dimasciput @carina1000 : Can we change the markers on the map for sites to squares so that the difference is clear for e.g. colour blind people and can be referred to generically without reference to colour?

Thanks

Tim

**Comment by timlinux** [comment]
I would propose to add a little [?] Icon at the bottom of the toolbar with the tooltip: Map navigation help

**Comment by carina1000** [comment]
Yes @Tim please see ticket #258
